version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: test 
    ports:
      - 15432:5432
    restart: always
